export const TOGGLE_SIDEBAR = 'Layout/TOGGLE_SIDEBAR';

export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';

export const RECEIVE_DASHBOARD = 'RECEIVE_DASHBOARD';

export const DASHBOARD_QUERY_ERR = 'DASHBOARD_QUERY_ERR';
